blank_issues_enabled: false

contact_links:
  - name: Support Request
    url: https://github.com/kwihanganaemmy-tech/devops-capstone-project/discussions
    about: Please ask and answer questions here.

  - name: Documentation
    url: https://github.com/kwihanganaemmy-tech/devops-capstone-project/wiki
    about: Check the project documentation.
